spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

jwt:
  key: fdsafdsafdsafdsafdsafdsafdsafdsafdsafdsafda
  access:
    expiration: 1
  refresh:
    expiration: 14

exclude-auth-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST
    - path-pattern: /api/users/logout
      method: DELETE
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs/**
      method: GET
    - path-pattern: /webjars/**
      method: GET
    - path-pattern: /actuator/**
      method: GET
    - path-pattern: /health
      method: GET
    - path-pattern: /**
      method: OPTIONS

exclude-blacklist-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs/**
      method: GET
    - path-pattern: /webjars/**
      method: GET
    - path-pattern: /actuator/**
      method: GET
    - path-pattern: /health
      method: GET
    - path-pattern: /**
      method: OPTIONS

cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "Authorization,Content-Type,Accept"
  max-age: 3600